### ISSUE TITLE
Numeric Buttons Missing from Module

### ISSUE THREAD

**Issue by mat-oshaughnessy** [bitfocus/companion-module-sony-broadcastmonitor#1]
Hi,

The Numeric button action is missing from the module. The option was there on past releases.

**Comment by daniep01** [comment]
Hi, I have installed the latest build (2.3.0 (2.3.0+4610-38a453f3)) and the buttons are there for me. There have not been any recent code changes.

![image](https://user-images.githubusercontent.com/17852298/186472720-411d5809-4d0d-4a09-a244-380c8d8f3430.png)

**Comment by mat-oshaughnessy** [comment]
Right, it's under Generic button press.  Thank you!
