### ISSUE TITLE
Can adjusting of colorspace be implemented with this protocol?

### ISSUE THREAD

**Issue by fetchmeabanana** [bitfocus/companion-module-sony-broadcastmonitor#2]
Hello, as the title says; Is it possible implement this, or does the protocol not allow it?

**Comment by daniep01** [comment]
I can't see anything for colourspace in the spec document but you might be able to program a series of menu/up/down/enter actions to do it.

**Comment by fetchmeabanana** [comment]
Aha seems strange that it is not possible to do this, but then again Sony is very strange sometimes. Thank you for checking!

**Comment by daniep01** [comment]
It's possible I don't have the most up to date spec document, if you have any contacts at Sony you could ask them?
